[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public,max-age=60"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Strict-Transport-Security = "max-age=2592000;"
    Accept-CH = "Downlink,RTT,Device-Memory,Save-Data,DPR,Width"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = '''
    default-src 'self';
    img-src 'self' data:;
    script-src 'self' 'unsafe-inline' use.fontawesome.com;
    connect-src 'self';
    style-src 'self' 'unsafe-inline' stackpath.bootstrapcdn.com;
    child-src 'self';
    worker-src 'self';'''